name: Docker Image CI [arm64]

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.ENG_STD_TOKEN }}

jobs:
  setup-build-publish:
    name: Build and Push Docker image to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEVFLOWS_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEVFLOWS_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Compute Tag
        id: compute-tag
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: devflows/${{ github.repository }}
        run: |
          SHA=`echo ${GITHUB_SHA} | cut -c1-7`
          IMAGE_TAG=$(echo ${GITHUB_REF#refs/heads/}-${SHA}-amd64 | sed "s/[^[:alnum:]]/-/g")
          echo ::set-output name=tags::${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}

      - name: Copy Devflows Runtimes
        run: |
          aws s3 cp s3://devflows-function-framework/typescript/.dockerignore ./.devflows/.dockerignore
          aws s3 cp s3://devflows-function-framework/typescript/entry.sh ./.devflows/entry.sh
          aws s3 cp s3://devflows-function-framework/typescript/init.sh ./.devflows/init.sh
          aws s3 cp s3://devflows-function-framework/typescript/Dockerfile ./.devflows/Dockerfile
          aws s3 cp s3://devflows-function-framework/typescript/server.ts ./.devflows/server.ts
          aws s3 cp s3://devflows-function-framework/typescript/action-server.ts ./.devflows/action-server.ts
          aws s3 cp s3://devflows-function-framework/typescript/index.ts ./.devflows/index.ts
          aws s3 cp s3://devflows-function-framework/extensions/logs-extension ./.devflows/extensions/logs-extension
          aws s3 cp s3://devflows-function-framework/mini-proxy/mini-proxy ./.devflows/mini-proxy

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/amd64
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push to ECR
        env:
          tags: ${{ steps.compute-tag.outputs.tags }}
        run: |
          docker buildx build --push --platform linux/amd64 --tag ${tags} -f .devflows/Dockerfile --build-arg GITHUB_TOKEN --build-arg GITHUB_REPOSITORY --build-arg GITHUB_RUN_ID .
          
      - name: Log out of Amazon ECR
        if: always()
        run: docker logout ${{ steps.login-ecr.outputs.registry }}
