# DO NOT update this file. It is supposed to be managed by devflows system only.

name: Docker Image CI [arm64]

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.ENG_STD_TOKEN }}

jobs:
  setup-build-publish:
    name: Build and Push Docker image to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEVFLOWS_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEVFLOWS_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Compute Tag
        run: |
          SHA=`echo ${GITHUB_SHA} | cut -c1-7`
          echo "IMAGE_TAG=$(echo ${GITHUB_REF#refs/heads/}-${SHA} | sed "s/[^[:alnum:]]/-/g")" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/arm64
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and Push to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: devflows/${{ github.repository }}
        run: |
          aws s3 cp s3://devflows-function-framework/arm-support-typescript/typescript/Dockerfile.arm64 ./.devflows/Dockerfile
          docker buildx build --push -f .devflows/Dockerfile --platform linux/arm64 --tag ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}-arm64 --build-arg GITHUB_TOKEN --build-arg GITHUB_REPOSITORY --build-arg GITHUB_RUN_ID .

      - name: Log out of Amazon ECR
        if: always()
        run: docker logout ${{ steps.login-ecr.outputs.registry }}
